---
title: "Digital History Methods"
subtitle: |
  HIST 5444 • Spring 2026<br>Virginia Tech
sidebar: false
toc: false
---

:::: {.grid .course-details}

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
### Instructor

- {{< fa user >}} [Jesse Sadler](https://www.jessesadler.com)
- {{< fa university >}} Newman Library 4064
:::

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
### Meetings

- {{< fa calendar >}} Mondays
- {{< fa clock >}} 2pm–4:50pm
- {{< fa location-dot >}} Athenaeum, Newman Library 124
:::

::: {.g-col-12 .g-col-md-4 .contact-policy}
### Contacting me

- {{< fa envelope >}} <a href='jrsadler@vt.edu'>jrsadler@vt.edu</a>
- {{< fa calendar-check >}} [Schedule an appointment](https://calendar.lib.vt.edu/appointments/jrsadler)

:::

::::

## Course description
This course will introduce students to computational methods for analyzing data to develop historical interpretations. You will work through the entire data life-cycle: finding, creating, cleaning, analyzing, visualizing, interpreting, and integrating these interpretations into your historical work. This will be done using free and open source programming languages and tools designed for data analysis, specifically we will be using the R programming language. This approach has a steeper learning curve than point-and-click tools that provide an alternative method for creating digital projects. However, it puts you in control, fosters transparency and reproducibility, and follows the guidelines of [minimal computing](https://go-dh.github.io/mincomp/about/). No previous experience with programming or data analysis is necessary. We will work through a series of examples using provided datasets, and then you will have the opportunity to apply the methods you have learned to your own research, culminating in the creation of a project website.

### Digital Scholarship Collaboration hour
- {{< fa circle-info >}} Students are encouraged to come to the [weekly collaboration hour](https://calendar.lib.vt.edu/event/16222034) held in the Athenaeum to work on assignments/projects and ask questions.
- {{< fa calendar >}} Thursdays
- {{< fa clock >}} 12pm–1:00pm
- {{< fa location-dot >}} Athenaeum Collaboration room, Newman Library 126

## Schedule
1. MLK Day (19 January)
2. History, data, and the digital (26 January)
3. The file system and Markdown (2 February)
4. "Tidy" historical data (9 February)
5. Visualizing data with ggplot2 (16 February)
6. Wrangling data (23 February)
7. Working with SNiGB (2 March)
8. Reproducible workflows with Git (16 March)
9. Making websites with Quarto (23 March)
10. Making maps (30 March)
11. Network analysis (6 April)
12. Web design and visualization (13 April)
13. Mapping and Network analysis (20 April)
14. Group work on your project (27 April)
15. Presentation of final projects (4 May)
