---
title: "Visualizing data with ggplot2"
subtitle: "16 February 2026"
format: html
---

*This week we dive into programming with R by learning to create visualizations with ggplot2 and learn how to run R code in RStudio.*

## Reading
- Kieran Healy, [Data Visualization: A Practical Introduction](https://socviz.co) (Princeton University Press, 2018), Chapters 1 and 3.
- Claus Wilke, [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) (O'Reilly 2019), Chapters 2 and 5.
- John Theibault, "Visualizations and Historical Arguments," in *Writing History in the Digital Age*, ed. Jack Dougherty and Kristen Nawrotzki (University of Michigan Press, 2013), <https://doi.org/10.3998/dh.12230987.0001.001>, 173–185.

## Watch
[Kieran Healy's](https://kieranhealy.org) keynote presentation at last year's Posit conference on Trustworthy Data Visualization: 

::: {.grid}

::: {.g-col-9}
{{< video https://youtu.be/ZamPCbvBAgE?si=HlR5phzzJwKr30ML >}}
:::

:::

## Assignment
- Create a [GitHub account](https://github.com). You can follow [these instructions](https://swcarpentry.github.io/git-novice/#creating-a-github-account) from the Carpentries. Choose a username that you would be ok sharing. Mine is jessesadler, and so I can be found at <https://github.com/jessesadler>.
    - Look through the [course website repository](https://github.com/jessesadler/vt5444s26) and [file an issue](https://github.com/jessesadler/vt5444s26/issues) about something that could be improved or where there is a mistake. It might be easiest to do this by looking at the course website and selecting Report an issue, which is usually on the right side of a page.
- Download R and RStudio
    - See the Resources section for instructions.
- Commonplace book writing: Reflect on the use of visualization in the humanities.

## Activities
- Worksheet: Getting started with visualization 
- Intro to RStudio
- Visualization with `ggplot2` in RStudio

## Resources

See Resources pages for RStudio and visualization.

### Working in RStudio
- [Wickham et al., *R for Data Science*](https://r4ds.hadley.nz), chapters 2, 6, and 8.
- [RStudio User Guide](https://docs.posit.co/ide/user/)

### Visualization
Make sure to look at the [ggplot2 website](https://ggplot2.tidyverse.org) that is full of great documentation and examples, including a [ggplot2 cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-visualization.pdf).

- [The Royal Statistical Society Data visualization Guide](https://royal-statistical-society.github.io/datavisguide/)
- [Wickham et al., *R for Data Science*](https://r4ds.hadley.nz), chapters 1, 9, 10, and 11.
- If you want some inspiration, look at [Nicola Rennie's](https://nrennie.rbind.io) visualization projects.
