---
title: "Reproducible workflows with Git"
subtitle: "16 March 2026"
format: html
---

*Setting aside R for the week, this week we will learn to use git and GitHub to develop reproducible workflows and get our work available on the internet.*

## Reading
- Hadley Wickham et al., [*R for Data Science*](https://r4ds.hadley.nz).
    - Chapter 28: Quarto
    - Chapter 16: Factors
    - Chapter 17: Dates and times
    - Chapter 18: Missing values
    - Chapter 19: Joins
- Jenny Bryan, "Excuse me, do you have a moment to talk about version control?," *PeerJ Preprints* (2017) <https://peerj.com/preprints/3159v2>.

## Assignment
- Install Git if you do not already have it installed on your computer.
    - Follow the instructions in [Resources: Installing Git](../resources/git-install.qmd).
- Practice data wrangling and visualization with R. You can:
    - Expand on your analysis of the SNiGB data in a Quarto document.
    - Start a data analysis project of your own based on data you have collected or found.
        - Create an RStudio project in your `hist5444s26/` folder. Set up the project as described in [Setting up RStudio for success](../resources/rstudio-setup.qmd#rstudio-projects).
        - What can you do with the data? What would you like to be able to do?
        - Reflect on what you have learned in a Quarto document and in your commonplace book.
- Think about setting goals for the rest of the semester.

## Activities
- Discussion of your data analysis project
- Getting familiar with the command line
- Getting started with git
- Working with git and GitHub in RStudio

## Resources
- [Git and GitHub: An overview](../resources/git-overview.qmd): This page contains more resources on Git and GitHub.
- [Installing Git](../resources/git-install.qmd)
- [Setting up Git and GitHub](../resources/git-setup.qmd)
- [The Git and GitHub workflow](../resources/git-workflow.qmd)
- [Git glossary](../resources/git-glossary.qmd)