---
title: "Making websites with Quarto"
subtitle: "23 March 2026"
format: html
---

*This week we begin to work on the final project for the course. We will work through creating a static website with Quarto and launching it using GitHub pages.*

## Reading
- Olivia Wikle and Evan Peter Williamson, "Static Web Methodology as a Sustainable Approach to Digital Humanities Projects," *The Code4Lib Journal*, no. 60 (April 2025), <https://journal.code4lib.org/articles/18372>.

## Watch
Mine Çetinkaya-Rundel & Julia Stewart Lowndes, Hello Quarto: Share, Collaborate, Teach, Reimagine at RStudio conf 2022.

::: {.grid}

::: {.g-col-9}
{{< video https://youtu.be/p7Hxu4coDl8?si=vWTopEp9-_0fZg8x >}}
:::

:::

## Assignment
- Try your best to get your `r-notes` project on GitHub following the Local first instructions on [The Git and GitHub workflow](../resources/git-workflow.qmd).
- Practice writing some R code.

## Activities
- Git and GitHub check in
- Quarto documents with SNiGB data
- Static websites
- Quarto websites

## Resources

### Quarto resources
- [Elen Le Foll, Quarto for reproducible research workflows and academic publishing](https://elenlefoll.quarto.pub/quarto4research/)
- [Branded Websites, Presentations, Dashboards, and PDFs with Quarto posit::conf(2025) workshop](https://posit-conf-2025.github.io/quarto-brand/)
- Quarto documentation: [Creating a website](https://quarto.org/docs/websites/)
- Quarto documentation: [HTML Documents](https://quarto.org/docs/output-formats/html-basics.html)

### DH and static websites
- *Digital Humanities Quarterly* special issue on [Minimal Computing](https://dhq.digitalhumanities.org/vol/16/2/index.html).
- [Lib-Static](https://lib-static.github.io).
- Amanda Visconti, "Building a Static Website with Jekyll and GitHub Pages," *The Programming Historian* (2016), <https://doi.org/10.46430/phen0048>.

### Static webistes
- Brian Rinaldi, *Static Site Generators* (O’Reilly Media, 2015), <https://learning.oreilly.com/library/view/static-site-generators/9781492048558/>.