---
title: "Mapping and network analysis"
subtitle: "20 April 2026"
format: html
---

## Reading
Background reading on mapping or network analysis. Find one or more sources that are related to what you want to do for your project. Add resources to the shared [Zotero Library](https://www.zotero.org/groups/6406819/vts/library).

## Assignment
- Create a quarto document that makes an analysis of data from your project.
- Commonplace book writing: What are you excited to work on? What skills do you need to concentrate on improving?

## Activities
- Discussion: What does DH look like as we approach the end of the semester?
- Workflow practice.
    - SNiGB network analysis: [Download this Quarto document to practice](../files/snigb-networks.qmd).
    - Mapping: Lines from points
- Introduction to interactive tables in Quarto

## Resources
- [Resources: Networks in R](../resources/networks.qmd)
- [Resources: Mapping in R](../resources/mapping.qmd)
- [Resources: Mapping: Creating lines from points](../resources/mapping-lines.qmd)
- [Resources: Interactive tables in Quarto](../resources/quarto-tables.qmd)