---
title: "Licensing and open access"
format: html
---

This page provides resources for licensing the open educational resources you create with the tools used in the course. Licensing is a complex topic, but generally content is shared under copyright or with a Creative Commons license such as [CC by 4.0](https://creativecommons.org/licenses/by/4.0/).

University Libraries at Virginia Tech provides a Research Guide on [Open Education](https://guides.lib.vt.edu/oer) that includes a section dedicated to [Creative Commons Licenses](https://guides.lib.vt.edu/oer/cc).

A license can be added to the [footer of a website](https://quarto.org/docs/websites/website-navigation.html#page-footer) or you can have copyright or license information in the [yaml front matter](https://quarto.org/docs/authoring/front-matter.html#copyright).

Another option is to create a `LICENSE.md` file in your repository. This is the recommendation from the [Good Enough Practices in Scientific Computing](https://usethis.r-lib.org/reference/licenses.html) lesson from the Carpentries.  The [usethis package](https://usethis.r-lib.org/reference/licenses.html) even provides functions that do this for you.
